"""empty message

Revision ID: 426dd46155cc
Revises: 89f5e8a2fa24
Create Date: 2025-08-21 12:01:30.770990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426dd46155cc'
down_revision = '89f5e8a2fa24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlineRoute',
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('airline_id', 'route_id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('routes_airline_id_fkey'), type_='foreignkey')
        batch_op.drop_column('airline_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airline_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('routes_airline_id_fkey'), 'airlines', ['airline_id'], ['id'])

    op.drop_table('airlineRoute')
    # ### end Alembic commands ###
