"""empty message

Revision ID: 63277afd2fc1
Revises: b14db61be0c0
Create Date: 2025-08-28 10:01:11.751658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63277afd2fc1'
down_revision = 'b14db61be0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircraft_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('seats_total', sa.Integer(), nullable=False),
    sa.Column('price_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_extras',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('extra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['aircraft_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'extra_id')
    )
    op.create_table('seats',
    sa.Column('nSeat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('occupied', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['aircraft_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nSeat')
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seats_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_flight_id'), ['flight_id'], unique=False)

    op.create_table('ticket_extras',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('extra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'extra_id')
    )
    with op.batch_alter_table('aircrafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircrafts_airline_id'), ['airline_id'], unique=False)

    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airlines_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_airlines_name'), ['name'], unique=False)

    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('airports_code_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('airports_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_airports_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_airports_name'), ['name'], unique=True)

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tickets_seat_id'), ['seat_id'], unique=True)
        batch_op.create_foreign_key(None, 'seats', ['seat_id'], ['nSeat'], ondelete='SET NULL')
        batch_op.drop_column('extras')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extras', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tickets_seat_id'))
        batch_op.drop_column('seat_id')

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('base_price')

    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airports_name'))
        batch_op.drop_index(batch_op.f('ix_airports_code'))
        batch_op.create_unique_constraint(batch_op.f('airports_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('airports_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airlines_name'))
        batch_op.drop_index(batch_op.f('ix_airlines_code'))

    with op.batch_alter_table('aircrafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircrafts_airline_id'))

    op.drop_table('ticket_extras')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_flight_id'))
        batch_op.drop_index(batch_op.f('ix_seats_class_id'))

    op.drop_table('seats')
    op.drop_table('class_extras')
    op.drop_table('aircraft_classes')
    op.drop_table('extras')
    # ### end Alembic commands ###
