"""empty message

Revision ID: 64b7d460d2a1
Revises: 9c1bf6103203
Create Date: 2025-08-26 09:11:30.774674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b7d460d2a1'
down_revision = '9c1bf6103203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('final_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
