"""empty message

Revision ID: 6d1f75d75286
Revises: 5539c9a61fb3
Create Date: 2025-08-21 10:07:58.860767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1f75d75286'
down_revision = '5539c9a61fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('airlines_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('airlines_id_fkey'), 'users', ['id'], ['id'])

    # ### end Alembic commands ###
