"""empty message

Revision ID: b14db61be0c0
Revises: 64b7d460d2a1
Create Date: 2025-08-26 09:47:01.592938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14db61be0c0'
down_revision = '64b7d460d2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_flight_id'), ['flight_id'], unique=False)
        batch_op.create_index('ix_tickets_flight_passenger', ['flight_id', 'passenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_passenger_id'), ['passenger_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_passenger_id'))
        batch_op.drop_index('ix_tickets_flight_passenger')
        batch_op.drop_index(batch_op.f('ix_tickets_flight_id'))

    # ### end Alembic commands ###
